version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/weddinggram-app

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
  - object: /home/ubuntu/weddinggram-app/bin
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 777
    type: 
      -file

hooks:
  ApplicationStop:
    - location: bin/stop
      timeout: 300
      runas: ubuntu

  DownloadBundle:
    - location: bin/install-pkgs
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: bin/start
      timeout: 300
      runas: ubuntu

  ValidateService:
    - location: bin/status
      timeout: 300
      runas: ubuntu

  BeforeInstall:
    - location: bin/backup
      timeout: 300
      runas: ubuntu
