# This is a sample build configuration for Javascript.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:4.6.0

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - wget https://bootstrap.pypa.io/get-pip.py
          - python get-pip.py
          - pip install boto3==1.3.0
          - pwd
          - ls
          - apt-get install zip
          - python zip.py
          #- wget https://bitbucket.org/kenken77/day-20-demo-weddinggram-auth/get/8e573831a681.zip -o weddinggram.zip
          - python s3_upload.py weddinggram weddinggram.zip weddinggram-dev-deploy.zip
